services:
  - type: web
    name: lhb-tracker
    runtime: python
    branch: dev
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /healthz
    envVars:
      - key: DXX_USERNAME
        sync: false
      - key: DXX_PASSWORD
        sync: false
